database:
  path: "news.db"

scrapers:
  enable_static: true
  enable_dynamic: true
  enable_scrapy: true

logging:
  level: "INFO"
  file: "project.log"
  console: false

scraper_settings:
  throttle_min: 1
  throttle_max: 3
